const router = require('express').Router()
const UserController = require('../controllers/user')
const TodoController = require('../controllers/todo')
const Authentication = require('../middlewares/authentication')
const GoogleCheckUser = require('../middlewares/gSignIn')
const Authorization = require('../middlewares/authorization')
const {upload} = require('../helpers/images')
router.post('/signup', UserController.create)
router.post('/gsignin', GoogleCheckUser, UserController.createUserGoogle)
router.post('/login', UserController.login)

router.post('/upload', upload.single('image'),  TodoController.images)
router.post('/todos',  Authentication,TodoController.create)
router.get('/todos', Authentication, TodoController.readAll)
router.get('/todos/:id', Authentication, TodoController.readOne)
router.patch('/todos/:id', Authentication, Authorization, TodoController.update)
router.delete('/todos/:id', Authentication, Authorization ,TodoController.delete)
module.exports = router